# Generated by Django 4.0.2 on 2022-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowid', models.IntegerField(default=0)),
                ('Userid', models.IntegerField(default=0)),
                ('teamid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.IntegerField(default=0)),
                ('teamname', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=256)),
                ('Userid', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
    ]
